//! Exact ATC catalog available to 1601EQ January 2018 (ENCS).
//!
//! Grounding:
//! - Offline eBIRForms 7.9.6 `xml/atcCodes.xml`, 153,753 bytes,
//!   SHA-256 `16e4db6ce456a6fb0a97f085cf8ef19349c2f6fc183971e97d4e253f63cdd22b`;
//! - `loadXMLATC('xml/atcCodes.xml')` line 1522, `loadATC` lines 1638-1680,
//!   `getWithholdingAgentATC` lines 2643-2662, `changeATCRate` lines
//!   2665-2692.
//!
//! The whole chain lives in the HTA, so this catalog does not depend on the
//! seven scripts 1601EQ fails to load. Rendering the rows does
//! (`formatCurrency` is in the absent `bir-formatter.js`), so this module
//! pins the lookup domain only.
//!
//! `loadATC` keeps a record when the raw text contains the substring
//! `1601EQ` and reads only fields 0-3 as code, description, rate and
//! category; it hardcodes base, compType, constTaxDue, minimum and maximum
//! to the empty string, so those XML columns are never consulted.
//!
//! `getWithholdingAgentATC` then narrows by `category == "P"` or `"G"`, so
//! the lookup key is the pair, not the code alone: 96 codes appear once in
//! each category.
//!
//! Four records tagged `1601EQ` are malformed in the source and carry only
//! nine fields: their rate is written into the description after a
//! semicolon instead of occupying its own `~` column. `loadATC` therefore
//! reads their category as the rate and leaves the category empty, and
//! `getWithholdingAgentATC` drops them from both dropdowns. They are
//! recorded in `unreachable_records` rather than silently omitted.

const std = @import("std");
const validation = @import("validation.zig");

pub const source_byte_length: usize = 153_753;
pub const source_sha256 =
    "16e4db6ce456a6fb0a97f085cf8ef19349c2f6fc183971e97d4e253f63cdd22b";

/// `atcCount` declared by the file header.
pub const declared_atc_count: usize = 1085;
/// Records passing `loadATC`'s `indexOf('1601EQ')` test.
pub const matched_record_count: usize = 211;

pub const Category = enum {
    private,
    government,

    /// `getWithholdingAgentATC` compares against the `optCategory` value.
    pub fn token(self: Category) []const u8 {
        return switch (self) {
            .private => "P",
            .government => "G",
        };
    }

    pub fn fromIdentity(category: validation.Category) ?Category {
        return switch (category) {
            .private => .private,
            .government => .government,
            .none => null,
        };
    }
};

pub const AtcRecord = struct {
    code: []const u8,
    description: []const u8,
    /// Verbatim from the source column. Not parsed here: the HTA passes the
    /// string through `changeATCRate` and into the DOM without arithmetic.
    rate: []const u8,
    category: Category,
};

/// Malformed source record that `getWithholdingAgentATC` can never surface.
pub const UnreachableRecord = struct {
    code: []const u8,
    /// Carries the rate inline, which is why the column layout shifts.
    description: []const u8,
};

pub const records = [_]AtcRecord{
    .{ .code = "WI010", .description = "PROFESSIONAL (LAWYERS, CPAS, ENGINEERS, ETC.) - IF GROSS INCOME FOR THE CURRENT YEAR DID NOT EXCEED P 3M", .rate = "5.0", .category = .private },
    .{ .code = "WI011", .description = "PROFESSIONAL (LAWYERS, CPAS, ENGINEERS, ETC.) - IF GROSS INCOME IS MORE THAN P 3M OR VAT REGISTERED REGARDLESS OF AMOUNT", .rate = "10.0", .category = .private },
    .{ .code = "WI020", .description = "PROFESSIONAL ENTERTAINERS SUCH AS, BUT NOT LIMITED TO ACTORS AND ACTRESSES, SINGERS, LYRICISTS, COMPOSERS, EMCEES - IF GROSS INCOME FOR THE CURRENT YEAR DID NOT EXCEED P 3M", .rate = "5.0", .category = .private },
    .{ .code = "WI021", .description = "PROFESSIONAL ENTERTAINERS SUCH AS, BUT NOT LIMITED TO ACTORS AND ACTRESSES, SINGERS, LYRICISTS, COMPOSERS, EMCEES - IF GROSS INCOME IS MORE THAN P 3M OR VAT REGISTERED REGARDLESS OF AMOUNT", .rate = "10.0", .category = .private },
    .{ .code = "WI030", .description = "PROFESSIONAL ATHLETES INCLUDING BASKETBALL PLAYERS, PELOTARIS AND JOCKEYS - IF GROSS INCOME FOR THE CURRENT YEAR DID NOT EXCEED P 3M", .rate = "5.0", .category = .private },
    .{ .code = "WI031", .description = "PROFESSIONAL ATHLETES INCLUDING BASKETBALL PLAYERS, PELOTARIS AND JOCKEYS - IF GROSS INCOME IS MORE THAN P 3M OR VAT REGISTERED REGARDLESS OF AMOUNT", .rate = "10.0", .category = .private },
    .{ .code = "WI040", .description = "ALL DIRECTORS AND PRODUCERS INVOLVED IN MOVIES, STAGE, RADIO, TELEVISION AND MUSICAL PRODUCTIONS - IF GROSS INCOME FOR THE CURRENT YEAR DID NOT EXCEED P 3M", .rate = "5.0", .category = .private },
    .{ .code = "WI041", .description = "ALL DIRECTORS AND PRODUCERS INVOLVED IN MOVIES, STAGE, RADIO, TELEVISION AND MUSICAL PRODUCTIONS - IF GROSS INCOME IS MORE THAN P 3M OR VAT REGISTERED REGARDLESS OF AMOUNT", .rate = "10.0", .category = .private },
    .{ .code = "WI050", .description = "MANAGEMENT AND TECHNICAL CONSULTANTS - IF GROSS INCOME FOR THE CURRENT YEAR DID NOT EXCEED P 3M", .rate = "5.0", .category = .private },
    .{ .code = "WI051", .description = "MANAGEMENT AND TECHNICAL CONSULTANTS - IF GROSS INCOME IS MORE THAN P 3M OR VAT REGISTERED REGARDLESS OF AMOUNT", .rate = "10.0", .category = .private },
    .{ .code = "WI060", .description = "BUSINESS AND BOOKKEEPING AGENTS AND AGENCIES - IF GROSS INCOME FOR THE CURRENT YEAR DID NOT EXCEED P 3M", .rate = "5.0", .category = .private },
    .{ .code = "WI061", .description = "BUSINESS AND BOOKKEEPING AGENTS AND AGENCIES -IF GROSS INCOME IS MORE THAN P 3M OR VAT REGISTERED REGARDLESS OF AMOUNT", .rate = "10.0", .category = .private },
    .{ .code = "WI070", .description = "INSURANCE AGENTS AND INSURANCE ADJUSTERS - IF GROSS INCOME FOR THE CURRENT YEAR DID NOT EXCEED P 3M", .rate = "5.0", .category = .private },
    .{ .code = "WI071", .description = "INSURANCE AGENTS AND INSURANCE ADJUSTERS - IF GROSS INCOME IS MORE THAN P 3M OR VAT REGISTERED REGARDLESS OF AMOUNT", .rate = "10.0", .category = .private },
    .{ .code = "WI080", .description = "OTHER RECIPIENTS OF TALENT FEES - IF GROSS INCOME FOR THE CURRENT YEAR DID NOT EXCEED P 3M", .rate = "5.0", .category = .private },
    .{ .code = "WI081", .description = "OTHER RECIPIENTS OF TALENT FEES - IF GROSS INCOME IS MORE THAN P 3M OR VAT REGISTERED REGARDLESS OF AMOUNT", .rate = "10.0", .category = .private },
    .{ .code = "WI090", .description = "FEES OF DIRECTORS WHO ARE NOT EMPLOYEES OF THE COMPANY - IF GROSS INCOME FOR THE CURRENT YEAR DID NOT EXCEED P 3M", .rate = "5.0", .category = .private },
    .{ .code = "WI091", .description = "FEES OF DIRECTORS WHO ARE NOT EMPLOYEES OF THE COMPANY - IF GROSS INCOME IS MORE THAN P 3M OR VAT REGISTERED REGARDLESS OF AMOUNT", .rate = "10.0", .category = .private },
    .{ .code = "WI100", .description = "RENTALS: ON GROSS RENTAL OR LEASE FOR THE CONTINUED USE OR POSSESSION OF PERSONAL PROPERTY IN EXCESS OF TEN THOUSAND PESOS (P 10,000) ANNUALLY AND REAL PROPERTY USED IN BUSINESS WHICH THE PAYOR OR OBLIGOR HAS NOT TAKEN TITLE OR IS NOT TAKING TITLE, OR IN WHICH HAS NO EQUITY; POLES, SATELLITES , TRANSMISSION FACILITIES AND BILLBOARDS", .rate = "5.0", .category = .private },
    .{ .code = "WI110", .description = "CINEMATOGRAPHIC FILM RENTALS AND OTHER PAYMENTS TO RESIDENT INDIVIDUALS AND CORPORATE CINEMATOGRAPHIC FILM OWNERS, LESSORS OR DISTRIBUTORS", .rate = "5.0", .category = .private },
    .{ .code = "WI120", .description = "INCOME PAYMENTS TO CERTAIN CONTRACTORS ", .rate = "2.0", .category = .private },
    .{ .code = "WI130", .description = "INCOME DISTRIBUTION TO THE BENEFICIARIES OF ESTATES AND TRUSTS", .rate = "15.0", .category = .private },
    .{ .code = "WI139", .description = "GROSS COMMISSIONS OR SERVICE FEES OF CUSTOMS, INSURANCE, STOCK, IMMIGRATION AND COMMERCIAL BROKERS, FEES OF AGENTS OF PROFESSIONAL ENTERTAINERS AND REAL ESTATE SERVICE PRACTITIONERS (RESPS), (I.E. REAL ESTATE CONSULTANTS, REAL ESTATE APPRAISERS AND REAL ESTATE BROKERS) - IF GROSS INCOME FOR THE CURRENT YEAR DID NOT EXCEED P 3M", .rate = "5.0", .category = .private },
    .{ .code = "WI140", .description = "GROSS COMMISSIONS OR SERVICE FEES OF CUSTOMS, INSURANCE, STOCK, IMMIGRATION AND COMMERCIAL BROKERS, FEES OF AGENTS OF PROFESSIONAL ENTERTAINERS AND REAL ESTATE SERVICE PRACTITIONERS (RESPS), (I.E. REAL ESTATE CONSULTANTS, REAL ESTATE APPRAISERS AND REAL ESTATE BROKERS) -  IF GROSS INCOME IS MORE THAN P 3M OR VAT REGISTERED REGARDLESS OF AMOUNT", .rate = "10.0", .category = .private },
    .{ .code = "WI150", .description = "PROFESSIONAL FEES PAID TO MEDICAL PRACTITIONERS (INCLUDES DOCTORS OF MEDICINE, DOCTORS OF VETERINARY SCIENCE & DENTISTS) BY HOSPITALS & CLINICS OR PAID DIRECTLY BY HEALTH MAINTENANCE ORGANIZATIONS (HMOS) AND/OR SIMILAR ESTABLISHMENTS - IF GROSS INCOME IS MORE THAN P 3M OR VAT REGISTERED REGARDLESS OF AMOUNT", .rate = "10.0", .category = .private },
    .{ .code = "WI151", .description = "PROFESSIONAL FEES PAID TO MEDICAL PRACTITIONERS (INCLUDES DOCTORS OF MEDICINE, DOCTORS OF VETERINARY SCIENCE & DENTISTS) BY HOSPITALS & CLINICS OR PAID DIRECTLY BY HEALTH MAINTENANCE ORGANIZATIONS (HMOS) AND/OR SIMILAR ESTABLISHMENTS - IF GROSS INCOME FOR THE CURRENT YEAR DID NOT EXCEED P 3M", .rate = "5.0", .category = .private },
    .{ .code = "WI152", .description = "PAYMENT BY THE GENERAL PROFESSIONAL PARTNERSHIPS (GPPS) TO ITS PARTNERS - IF GROSS INCOME FOR THE CURRENT YEAR DID NOT EXCEED P 720,000", .rate = "10.0", .category = .private },
    .{ .code = "WI153", .description = "PAYMENT BY THE GENERAL PROFESSIONAL PARTNERSHIPS (GPPS) TO ITS PARTNERS - IF GROSS INCOME EXCEEDS P 720,000", .rate = "15.0", .category = .private },
    .{ .code = "WI156", .description = "INCOME PAYMENTS MADE BY CREDIT CARD COMPANIES", .rate = "0.5", .category = .private },
    .{ .code = "WI640", .description = "INCOME PAYMENTS MADE BY THE GOVERNMENT AND GOVERNMENT-OWNED AND CONTROLLED CORPORATIONS (GOCCS) TO ITS LOCAL/RESIDENT SUPPLIERS OF GOODS OTHER THAN THOSE COVERED BY OTHER RATES OF WITHHOLDING TAX", .rate = "1.0", .category = .private },
    .{ .code = "WI157", .description = "INCOME PAYMENTS MADE BY THE GOVERNMENT AND GOVERNMENT-OWNED AND CONTROLLED CORPORATIONS (GOCCS) TO ITS LOCAL/RESIDENT SUPPLIERS OF SERVICES OTHER THAN THOSE COVERED BY OTHER RATES OF WITHHOLDING TAX", .rate = "2.0", .category = .private },
    .{ .code = "WI159", .description = "ADDITIONAL INCOME PAYMENTS TO GOVERNMENT PERSONNEL FROM IMPORTERS, SHIPPING AND AIRLINE COMPANIES OR THEIR AGENTS FOR OVERTIME SERVICES", .rate = "15.0", .category = .private },
    .{ .code = "WI158", .description = "INCOME PAYMENT MADE BY TOP WITHHOLDING AGENTS TO THEIR LOCAL/RESIDENT SUPPLIER OF GOODS OTHER THAN THOSE COVERED BY OTHER RATES OF WITHHOLDING TAX", .rate = "1.0", .category = .private },
    .{ .code = "WI160", .description = "INCOME PAYMENT MADE BY TOP WITHHOLDING AGENTS TO THEIR LOCAL/RESIDENT SUPPLIER OF SERVICES OTHER THAN THOSE COVERED BY OTHER RATES OF WITHHOLDING TAX", .rate = "2.0", .category = .private },
    .{ .code = "WI515", .description = "COMMISSIONS, REBATES, DISCOUNTS AND OTHER SIMILAR CONSIDERATIONS PAID/GRANTED TO INDEPENDENT AND/OR EXCLUSIVE SALES REPRESENTATIVES AND MARKETING AGENTS AND SUB-AGENTS OF COMPANIES, INCLUDING MULTI-LEVEL MARKETING COMPANIES - IF GROSS INCOME FOR THE CURRENT YEAR DID NOT EXCEED P 3M", .rate = "5.0", .category = .private },
    .{ .code = "WI516", .description = "COMMISSIONS, REBATES, DISCOUNTS AND OTHER SIMILAR CONSIDERATIONS PAID/GRANTED TO INDEPENDENT AND/OR EXCLUSIVE SALES REPRESENTATIVES AND MARKETING AGENTS AND SUB-AGENTS OF COMPANIES, INCLUDING MULTI-LEVEL MARKETING COMPANIES - IF GROSS INCOME IS MORE THAN P 3M OR VAT REGISTERED REGARDLESS OF AMOUNT", .rate = "10.0", .category = .private },
    .{ .code = "WI530", .description = "GROSS PAYMENTS TO EMBALMERS BY FUNERAL PARLORS", .rate = "1.0", .category = .private },
    .{ .code = "WI535", .description = "PAYMENTS MADE BY PRE-NEED COMPANIES TO FUNERAL PARLORS", .rate = "1.0", .category = .private },
    .{ .code = "WI540", .description = "TOLLING FEES PAID TO REFINERIES", .rate = "5.0", .category = .private },
    .{ .code = "WI610", .description = "INCOME PAYMENTS MADE TO SUPPLIERS OF AGRICULTURAL PRODUCTS IN EXCESS OF CUMULATIVE AMOUNT OF P 300,000 WITHIN THE SAME TAXABLE YEAR", .rate = "1.0", .category = .private },
    .{ .code = "WI630", .description = "INCOME PAYMENTS ON PURCHASES OF MINERALS, MINERAL PRODUCTS AND QUARRY RESOURCES, SUCH AS BUT NOT LIMITED TO SILVER, GOLD, MARBLE, GRANITE, GRAVEL, SAND, BOULDERS AND OTHER MINERAL PRODUCTS EXCEPT PURCHASES BY BANGKO SENTRAL NG PILIPINAS ", .rate = "5.0", .category = .private },
    .{ .code = "WI632", .description = "INCOME PAYMENTS ON PURCHASES OF MINERALS, MINERAL PRODUCTS AND QUARRY RESOURCES BY BANGKO SENTRAL NG PILIPINAS (BSP) FROM GOLD MINERS/SUPPLIERS UNDER PD 1899, AS AMENDED BY RA NO. 7076", .rate = "1.0", .category = .private },
    .{ .code = "WI650", .description = "ON GROSS AMOUNT OF REFUND GIVEN BY MERALCO TO CUSTOMERS WITH ACTIVE CONTRACTS AS CLASSIFIED BY MERALCO", .rate = "15.0", .category = .private },
    .{ .code = "WI651", .description = "ON GROSS AMOUNT OF REFUND GIVEN BY MERALCO TO CUSTOMERS WITH TERMINATED CONTRACTS AS CLASSIFIED BY MERALCO", .rate = "15.0", .category = .private },
    .{ .code = "WI660", .description = "ON GROSS AMOUNT OF INTEREST ON THE REFUND OF METER DEPOSIT WHETHER PAID DIRECTLY TO THE CUSTOMERS OR APPLIED AGAINST CUSTOMER'S BILLINGS OF RESIDENTIAL AND GENERAL SERVICE CUSTOMERS WHOSE MONTHLY ELECTRICITY CONSUMPTION EXCEEDS 200 KWH AS CLASSIFIED BY MERALCO", .rate = "10.0", .category = .private },
    .{ .code = "WI661", .description = "ON GROSS AMOUNT OF INTEREST ON THE REFUND OF METER DEPOSIT WHETHER PAID DIRECTLY TO THE CUSTOMERS OR APPLIED AGAINST CUSTOMER'S BILLINGS OF  NON-RESIDENTIAL CUSTOMERS WHOSE MONTHLY ELECTRICITY CONSUMPTION EXCEEDS 200 KWH AS CLASSIFIED BY MERALCO", .rate = "10.0", .category = .private },
    .{ .code = "WI662", .description = "ON GROSS AMOUNT OF INTEREST ON THE REFUND OF METER DEPOSIT WHETHER PAID DIRECTLY TO THE CUSTOMERS OR APPLIED AGAINST CUSTOMER'S BILLINGS OF RESIDENTIAL AND GENERAL SERVICE CUSTOMERS WHOSE MONTHLY ELECTRICITY CONSUMPTION EXCEEDS 200 KWH AS CLASSIFIED BY OTHER ELECTRIC DISTRIBUTION UTILITIES (DU)", .rate = "10.0", .category = .private },
    .{ .code = "WI663", .description = "ON GROSS AMOUNT OF INTEREST ON THE REFUND OF METER DEPOSIT WHETHER PAID DIRECTLY TO THE CUSTOMERS OR APPLIED AGAINST CUSTOMER'S ILLINGS OF  NON-RESIDENTIAL CUSTOMERS WHOSE MONTHLY ELECTRICITY CONSUMPTION EXCEEDS 200 KWH AS CLASSIFIED BY OTHER ELECTRIC DISTRIBUTION UTILITIES (DU)", .rate = "15.0", .category = .private },
    .{ .code = "WI680", .description = "INCOME PAYMENTS MADE BY POLITICAL PARTIES AND CANDIDATES OF LOCAL AND NATIONAL ELECTIONS ON ALL THEIR PURCHASES OF GOODS AND SERVICES RELATED TO CAMPAIGN EXPENDITURES, AND INCOME PAYMENTS MADE BY INDIVIDUALS OR JURIDICAL PERSONS FOR THEIR PURCHASES OF GOODS AND SERVICES INTENDED TO BE GIVEN AS CAMPAIGN CONTRIBUTIONS TO POLITICAL PARTIES AND CANDIDATES", .rate = "5.0", .category = .private },
    .{ .code = "WI710", .description = "INTEREST INCOME DERIVED FROM ANY OTHER DEBT INSTRUMENTS NOT WITHIN THE COVERAGE OF DEPOSIT SUBSTITUTES AND REVENUE REGULATIONS NO. 14-2012 ", .rate = "15.0", .category = .private },
    .{ .code = "WI720", .description = "INCOME PAYMENTS ON LOCALLY PRODUCED RAW SUGAR", .rate = "1.0", .category = .private },
    .{ .code = "WI010", .description = "PROFESSIONAL (LAWYERS, CPAS, ENGINEERS, ETC.) - IF GROSS INCOME FOR THE CURRENT YEAR DID NOT EXCEED P 3M", .rate = "5.0", .category = .government },
    .{ .code = "WI011", .description = "PROFESSIONAL (LAWYERS, CPAS, ENGINEERS, ETC.) - IF GROSS INCOME IS MORE THAN P 3M OR VAT REGISTERED REGARDLESS OF AMOUNT", .rate = "10.0", .category = .government },
    .{ .code = "WI020", .description = "PROFESSIONAL ENTERTAINERS SUCH AS, BUT NOT LIMITED TO ACTORS AND ACTRESSES, SINGERS, LYRICISTS, COMPOSERS, EMCEES - IF GROSS INCOME FOR THE CURRENT YEAR DID NOT EXCEED P 3M", .rate = "5.0", .category = .government },
    .{ .code = "WI021", .description = "PROFESSIONAL ENTERTAINERS SUCH AS, BUT NOT LIMITED TO ACTORS AND ACTRESSES, SINGERS, LYRICISTS, COMPOSERS, EMCEES - IF GROSS INCOME IS MORE THAN P 3M OR VAT REGISTERED REGARDLESS OF AMOUNT", .rate = "10.0", .category = .government },
    .{ .code = "WI030", .description = "PROFESSIONAL ATHLETES INCLUDING BASKETBALL PLAYERS, PELOTARIS AND JOCKEYS - IF GROSS INCOME FOR THE CURRENT YEAR DID NOT EXCEED P 3M", .rate = "5.0", .category = .government },
    .{ .code = "WI031", .description = "PROFESSIONAL ATHLETES INCLUDING BASKETBALL PLAYERS, PELOTARIS AND JOCKEYS - IF GROSS INCOME IS MORE THAN P 3M OR VAT REGISTERED REGARDLESS OF AMOUNT", .rate = "10.0", .category = .government },
    .{ .code = "WI040", .description = "ALL DIRECTORS AND PRODUCERS INVOLVED IN MOVIES, STAGE, RADIO, TELEVISION AND MUSICAL PRODUCTIONS - IF GROSS INCOME FOR THE CURRENT YEAR DID NOT EXCEED P 3M", .rate = "5.0", .category = .government },
    .{ .code = "WI041", .description = "ALL DIRECTORS AND PRODUCERS INVOLVED IN MOVIES, STAGE, RADIO, TELEVISION AND MUSICAL PRODUCTIONS - IF GROSS INCOME IS MORE THAN P 3M OR VAT REGISTERED REGARDLESS OF AMOUNT", .rate = "10.0", .category = .government },
    .{ .code = "WI050", .description = "MANAGEMENT AND TECHNICAL CONSULTANTS - IF GROSS INCOME FOR THE CURRENT YEAR DID NOT EXCEED P 3M", .rate = "5.0", .category = .government },
    .{ .code = "WI051", .description = "MANAGEMENT AND TECHNICAL CONSULTANTS - IF GROSS INCOME IS MORE THAN P 3M OR VAT REGISTERED REGARDLESS OF AMOUNT", .rate = "10.0", .category = .government },
    .{ .code = "WI060", .description = "BUSINESS AND BOOKKEEPING AGENTS AND AGENCIES - IF GROSS INCOME FOR THE CURRENT YEAR DID NOT EXCEED P 3M", .rate = "5.0", .category = .government },
    .{ .code = "WI061", .description = "BUSINESS AND BOOKKEEPING AGENTS AND AGENCIES -IF GROSS INCOME IS MORE THAN P 3M OR VAT REGISTERED REGARDLESS OF AMOUNT", .rate = "10.0", .category = .government },
    .{ .code = "WI070", .description = "INSURANCE AGENTS AND INSURANCE ADJUSTERS - IF GROSS INCOME FOR THE CURRENT YEAR DID NOT EXCEED P 3M", .rate = "5.0", .category = .government },
    .{ .code = "WI071", .description = "INSURANCE AGENTS AND INSURANCE ADJUSTERS - IF GROSS INCOME IS MORE THAN P 3M OR VAT REGISTERED REGARDLESS OF AMOUNT", .rate = "10.0", .category = .government },
    .{ .code = "WI080", .description = "OTHER RECIPIENTS OF TALENT FEES - IF GROSS INCOME FOR THE CURRENT YEAR DID NOT EXCEED P 3M", .rate = "5.0", .category = .government },
    .{ .code = "WI081", .description = "OTHER RECIPIENTS OF TALENT FEES - IF GROSS INCOME IS MORE THAN P 3M OR VAT REGISTERED REGARDLESS OF AMOUNT", .rate = "10.0", .category = .government },
    .{ .code = "WI090", .description = "FEES OF DIRECTORS WHO ARE NOT EMPLOYEES OF THE COMPANY - IF GROSS INCOME FOR THE CURRENT YEAR DID NOT EXCEED P 3M", .rate = "5.0", .category = .government },
    .{ .code = "WI091", .description = "FEES OF DIRECTORS WHO ARE NOT EMPLOYEES OF THE COMPANY - IF GROSS INCOME IS MORE THAN P 3M OR VAT REGISTERED REGARDLESS OF AMOUNT", .rate = "10.0", .category = .government },
    .{ .code = "WI100", .description = "RENTALS: ON GROSS RENTAL OR LEASE FOR THE CONTINUED USE OR POSSESSION OF PERSONAL PROPERTY IN EXCESS OF TEN THOUSAND PESOS (P 10,000) ANNUALLY AND REAL PROPERTY USED IN BUSINESS WHICH THE PAYOR OR OBLIGOR HAS NOT TAKEN TITLE OR IS NOT TAKING TITLE, OR IN WHICH HAS NO EQUITY; POLES, SATELLITES , TRANSMISSION FACILITIES AND BILLBOARDS", .rate = "5.0", .category = .government },
    .{ .code = "WI110", .description = "CINEMATOGRAPHIC FILM RENTALS AND OTHER PAYMENTS TO RESIDENT INDIVIDUALS AND CORPORATE CINEMATOGRAPHIC FILM OWNERS, LESSORS OR DISTRIBUTORS", .rate = "5.0", .category = .government },
    .{ .code = "WI120", .description = "INCOME PAYMENTS TO CERTAIN CONTRACTORS ", .rate = "2.0", .category = .government },
    .{ .code = "WI130", .description = "INCOME DISTRIBUTION TO THE BENEFICIARIES OF ESTATES AND TRUSTS", .rate = "15.0", .category = .government },
    .{ .code = "WI139", .description = "GROSS COMMISSIONS OR SERVICE FEES OF CUSTOMS, INSURANCE, STOCK, IMMIGRATION AND COMMERCIAL BROKERS, FEES OF AGENTS OF PROFESSIONAL ENTERTAINERS AND REAL ESTATE SERVICE PRACTITIONERS (RESPS), (I.E. REAL ESTATE CONSULTANTS, REAL ESTATE APPRAISERS AND REAL ESTATE BROKERS) - IF GROSS INCOME FOR THE CURRENT YEAR DID NOT EXCEED P 3M", .rate = "5.0", .category = .government },
    .{ .code = "WI140", .description = "GROSS COMMISSIONS OR SERVICE FEES OF CUSTOMS, INSURANCE, STOCK, IMMIGRATION AND COMMERCIAL BROKERS, FEES OF AGENTS OF PROFESSIONAL ENTERTAINERS AND REAL ESTATE SERVICE PRACTITIONERS (RESPS), (I.E. REAL ESTATE CONSULTANTS, REAL ESTATE APPRAISERS AND REAL ESTATE BROKERS) -  IF GROSS INCOME IS MORE THAN P 3M OR VAT REGISTERED REGARDLESS OF AMOUNT", .rate = "10.0", .category = .government },
    .{ .code = "WI150", .description = "PROFESSIONAL FEES PAID TO MEDICAL PRACTITIONERS (INCLUDES DOCTORS OF MEDICINE, DOCTORS OF VETERINARY SCIENCE & DENTISTS) BY HOSPITALS & CLINICS OR PAID DIRECTLY BY HEALTH MAINTENANCE ORGANIZATIONS (HMOS) AND/OR SIMILAR ESTABLISHMENTS - IF GROSS INCOME IS MORE THAN P 3M OR VAT REGISTERED REGARDLESS OF AMOUNT", .rate = "10.0", .category = .government },
    .{ .code = "WI151", .description = "PROFESSIONAL FEES PAID TO MEDICAL PRACTITIONERS (INCLUDES DOCTORS OF MEDICINE, DOCTORS OF VETERINARY SCIENCE & DENTISTS) BY HOSPITALS & CLINICS OR PAID DIRECTLY BY HEALTH MAINTENANCE ORGANIZATIONS (HMOS) AND/OR SIMILAR ESTABLISHMENTS - IF GROSS INCOME FOR THE CURRENT YEAR DID NOT EXCEED P 3M", .rate = "5.0", .category = .government },
    .{ .code = "WI152", .description = "PAYMENT BY THE GENERAL PROFESSIONAL PARTNERSHIPS (GPPS) TO ITS PARTNERS - IF GROSS INCOME FOR THE CURRENT YEAR DID NOT EXCEED P 720,000", .rate = "10.0", .category = .government },
    .{ .code = "WI153", .description = "PAYMENT BY THE GENERAL PROFESSIONAL PARTNERSHIPS (GPPS) TO ITS PARTNERS - IF GROSS INCOME EXCEEDS P 720,000", .rate = "15.0", .category = .government },
    .{ .code = "WI156", .description = "INCOME PAYMENTS MADE BY CREDIT CARD COMPANIES", .rate = "0.5", .category = .government },
    .{ .code = "WI640", .description = "INCOME PAYMENTS MADE BY THE GOVERNMENT AND GOVERNMENT-OWNED AND CONTROLLED CORPORATIONS (GOCCS) TO ITS LOCAL/RESIDENT SUPPLIERS OF GOODS OTHER THAN THOSE COVERED BY OTHER RATES OF WITHHOLDING TAX", .rate = "1.0", .category = .government },
    .{ .code = "WI157", .description = "INCOME PAYMENTS MADE BY THE GOVERNMENT AND GOVERNMENT-OWNED AND CONTROLLED CORPORATIONS (GOCCS) TO ITS LOCAL/RESIDENT SUPPLIERS OF SERVICES OTHER THAN THOSE COVERED BY OTHER RATES OF WITHHOLDING TAX", .rate = "2.0", .category = .government },
    .{ .code = "WI159", .description = "ADDITIONAL INCOME PAYMENTS TO GOVERNMENT PERSONNEL FROM IMPORTERS, SHIPPING AND AIRLINE COMPANIES OR THEIR AGENTS FOR OVERTIME SERVICES", .rate = "15.0", .category = .government },
    .{ .code = "WI158", .description = "INCOME PAYMENT MADE BY TOP WITHHOLDING AGENTS TO THEIR LOCAL/RESIDENT SUPPLIER OF GOODS OTHER THAN THOSE COVERED BY OTHER RATES OF WITHHOLDING TAX", .rate = "1.0", .category = .government },
    .{ .code = "WI160", .description = "INCOME PAYMENT MADE BY TOP WITHHOLDING AGENTS TO THEIR LOCAL/RESIDENT SUPPLIER OF SERVICES OTHER THAN THOSE COVERED BY OTHER RATES OF WITHHOLDING TAX", .rate = "2.0", .category = .government },
    .{ .code = "WI515", .description = "COMMISSIONS, REBATES, DISCOUNTS AND OTHER SIMILAR CONSIDERATIONS PAID/GRANTED TO INDEPENDENT AND/OR EXCLUSIVE SALES REPRESENTATIVES AND MARKETING AGENTS AND SUB-AGENTS OF COMPANIES, INCLUDING MULTI-LEVEL MARKETING COMPANIES - IF GROSS INCOME FOR THE CURRENT YEAR DID NOT EXCEED P 3M", .rate = "5.0", .category = .government },
    .{ .code = "WI516", .description = "COMMISSIONS, REBATES, DISCOUNTS AND OTHER SIMILAR CONSIDERATIONS PAID/GRANTED TO INDEPENDENT AND/OR EXCLUSIVE SALES REPRESENTATIVES AND MARKETING AGENTS AND SUB-AGENTS OF COMPANIES, INCLUDING MULTI-LEVEL MARKETING COMPANIES - IF GROSS INCOME IS MORE THAN P 3M OR VAT REGISTERED REGARDLESS OF AMOUNT", .rate = "10.0", .category = .government },
    .{ .code = "WI530", .description = "GROSS PAYMENTS TO EMBALMERS BY FUNERAL PARLORS", .rate = "1.0", .category = .government },
    .{ .code = "WI535", .description = "PAYMENTS MADE BY PRE-NEED COMPANIES TO FUNERAL PARLORS", .rate = "1.0", .category = .government },
    .{ .code = "WI540", .description = "TOLLING FEES PAID TO REFINERIES", .rate = "5.0", .category = .government },
    .{ .code = "WI610", .description = "INCOME PAYMENTS MADE TO SUPPLIERS OF AGRICULTURAL PRODUCTS IN EXCESS OF CUMULATIVE AMOUNT OF P 300,000 WITHIN THE SAME TAXABLE YEAR", .rate = "1.0", .category = .government },
    .{ .code = "WI630", .description = "INCOME PAYMENTS ON PURCHASES OF MINERALS, MINERAL PRODUCTS AND QUARRY RESOURCES, SUCH AS BUT NOT LIMITED TO SILVER, GOLD, MARBLE, GRANITE, GRAVEL, SAND, BOULDERS AND OTHER MINERAL PRODUCTS EXCEPT PURCHASES BY BANGKO SENTRAL NG PILIPINAS ", .rate = "5.0", .category = .government },
    .{ .code = "WI632", .description = "INCOME PAYMENTS ON PURCHASES OF MINERALS, MINERAL PRODUCTS AND QUARRY RESOURCES BY BANGKO SENTRAL NG PILIPINAS (BSP) FROM GOLD MINERS/SUPPLIERS UNDER PD 1899, AS AMENDED BY RA NO. 7076", .rate = "1.0", .category = .government },
    .{ .code = "WI650", .description = "ON GROSS AMOUNT OF REFUND GIVEN BY MERALCO TO CUSTOMERS WITH ACTIVE CONTRACTS AS CLASSIFIED BY MERALCO", .rate = "15.0", .category = .government },
    .{ .code = "WI651", .description = "ON GROSS AMOUNT OF REFUND GIVEN BY MERALCO TO CUSTOMERS WITH TERMINATED CONTRACTS AS CLASSIFIED BY MERALCO", .rate = "15.0", .category = .government },
    .{ .code = "WI660", .description = "ON GROSS AMOUNT OF INTEREST ON THE REFUND OF METER DEPOSIT WHETHER PAID DIRECTLY TO THE CUSTOMERS OR APPLIED AGAINST CUSTOMER'S BILLINGS OF RESIDENTIAL AND GENERAL SERVICE CUSTOMERS WHOSE MONTHLY ELECTRICITY CONSUMPTION EXCEEDS 200 KWH AS CLASSIFIED BY MERALCO", .rate = "10.0", .category = .government },
    .{ .code = "WI661", .description = "ON GROSS AMOUNT OF INTEREST ON THE REFUND OF METER DEPOSIT WHETHER PAID DIRECTLY TO THE CUSTOMERS OR APPLIED AGAINST CUSTOMER'S BILLINGS OF  NON-RESIDENTIAL CUSTOMERS WHOSE MONTHLY ELECTRICITY CONSUMPTION EXCEEDS 200 KWH AS CLASSIFIED BY MERALCO", .rate = "10.0", .category = .government },
    .{ .code = "WI662", .description = "ON GROSS AMOUNT OF INTEREST ON THE REFUND OF METER DEPOSIT WHETHER PAID DIRECTLY TO THE CUSTOMERS OR APPLIED AGAINST CUSTOMER'S BILLINGS OF RESIDENTIAL AND GENERAL SERVICE CUSTOMERS WHOSE MONTHLY ELECTRICITY CONSUMPTION EXCEEDS 200 KWH AS CLASSIFIED BY OTHER ELECTRIC DISTRIBUTION UTILITIES (DU)", .rate = "10.0", .category = .government },
    .{ .code = "WI663", .description = "ON GROSS AMOUNT OF INTEREST ON THE REFUND OF METER DEPOSIT WHETHER PAID DIRECTLY TO THE CUSTOMERS OR APPLIED AGAINST CUSTOMER'S BILLINGS OF  NON-RESIDENTIAL CUSTOMERS WHOSE MONTHLY ELECTRICITY CONSUMPTION EXCEEDS 200 KWH AS CLASSIFIED BY OTHER ELECTRIC DISTRIBUTION UTILITIES (DU)", .rate = "15.0", .category = .government },
    .{ .code = "WI680", .description = "INCOME PAYMENTS MADE BY POLITICAL PARTIES AND CANDIDATES OF LOCAL AND NATIONAL ELECTIONS ON ALL THEIR PURCHASES OF GOODS AND SERVICES RELATED TO CAMPAIGN EXPENDITURES, AND INCOME PAYMENTS MADE BY INDIVIDUALS OR JURIDICAL PERSONS FOR THEIR PURCHASES OF GOODS AND SERVICES INTENDED TO BE GIVEN AS CAMPAIGN CONTRIBUTIONS TO POLITICAL PARTIES AND CANDIDATES", .rate = "5.0", .category = .government },
    .{ .code = "WI710", .description = "INTEREST INCOME DERIVED FROM ANY OTHER DEBT INSTRUMENTS NOT WITHIN THE COVERAGE OF DEPOSIT SUBSTITUTES AND REVENUE REGULATIONS NO. 14-2012 ", .rate = "15.0", .category = .government },
    .{ .code = "WI720", .description = "INCOME PAYMENTS ON LOCALLY PRODUCED RAW SUGAR", .rate = "1.0", .category = .government },
    .{ .code = "WC010", .description = "PROFESSIONAL (LAWYERS, CPAS, ENGINEERS, ETC.) - IF GROSS INCOME FOR THE CURRENT YEAR DID NOT EXCEED P 720,000", .rate = "10.0", .category = .private },
    .{ .code = "WC011", .description = "PROFESSIONAL (LAWYERS, CPAS, ENGINEERS, ETC.) - IF GROSS INCOME EXCEEDS P 720,000", .rate = "15.0", .category = .private },
    .{ .code = "WC020", .description = "PROFESSIONAL ENTERTAINERS SUCH AS, BUT NOT LIMITED TO ACTORS AND ACTRESSES, SINGERS, LYRICISTS, COMPOSERS, EMCEES - IF GROSS INCOME FOR THE CURRENT YEAR DID NOT EXCEED P 720,000", .rate = "10.0", .category = .private },
    .{ .code = "WC021", .description = "PROFESSIONAL ENTERTAINERS SUCH AS, BUT NOT LIMITED TO ACTORS AND ACTRESSES, SINGERS, LYRICISTS, COMPOSERS, EMCEES - IF GROSS INCOME EXCEEDS P 720,000", .rate = "15.0", .category = .private },
    .{ .code = "WC030", .description = "PROFESSIONAL ATHLETES INCLUDING BASKETBALL PLAYERS, PELOTARIS AND JOCKEYS - IF GROSS INCOME FOR THE CURRENT YEAR DID NOT EXCEED P 720,000", .rate = "10.0", .category = .private },
    .{ .code = "WC031", .description = "PROFESSIONAL ATHLETES INCLUDING BASKETBALL PLAYERS, PELOTARIS AND JOCKEYS - IF GROSS INCOME EXCEEDS P 720,000", .rate = "15.0", .category = .private },
    .{ .code = "WC040", .description = "ALL DIRECTORS AND PRODUCERS INVOLVED IN MOVIES, STAGE, RADIO, TELEVISION AND MUSICAL PRODUCTIONS - IF GROSS INCOME FOR THE CURRENT YEAR DID NOT EXCEED P 720,000", .rate = "10.0", .category = .private },
    .{ .code = "WC041", .description = "ALL DIRECTORS AND PRODUCERS INVOLVED IN MOVIES, STAGE, RADIO, TELEVISION AND MUSICAL PRODUCTIONS -  IF GROSS INCOME EXCEEDS P 720,000", .rate = "15.0", .category = .private },
    .{ .code = "WC050", .description = "MANAGEMENT AND TECHNICAL CONSULTANTS - IF GROSS INCOME FOR THE CURRENT YEAR DID NOT EXCEED P 720,000", .rate = "10.0", .category = .private },
    .{ .code = "WC051", .description = "MANAGEMENT AND TECHNICAL CONSULTANTS - IF GROSS INCOME EXCEEDS P 720,000", .rate = "15.0", .category = .private },
    .{ .code = "WC060", .description = "BUSINESS AND BOOKKEEPING AGENTS AND AGENCIES - IF GROSS INCOME FOR THE CURRENT YEAR DID NOT EXCEED P 720,000", .rate = "10.0", .category = .private },
    .{ .code = "WC061", .description = "BUSINESS AND BOOKKEEPING AGENTS AND AGENCIES - IF GROSS INCOME EXCEEDS P 720,000", .rate = "15.0", .category = .private },
    .{ .code = "WC070", .description = "INSURANCE AGENTS AND INSURANCE ADJUSTERS - IF GROSS INCOME FOR THE CURRENT YEAR DID NOT EXCEED P 720,000", .rate = "10.0", .category = .private },
    .{ .code = "WC071", .description = "INSURANCE AGENTS AND INSURANCE ADJUSTERS - IF GROSS INCOME EXCEEDS P 720,000", .rate = "15.0", .category = .private },
    .{ .code = "WC080", .description = "OTHER RECIPIENTS OF TALENT FEES - IF GROSS INCOME FOR THE CURRENT YEAR DID NOT EXCEED P 720,000", .rate = "10.0", .category = .private },
    .{ .code = "WC081", .description = "OTHER RECIPIENTS OF TALENT FEES - IF GROSS INCOME EXCEEDS P 720,000", .rate = "15.0", .category = .private },
    .{ .code = "WC100", .description = "RENTALS: ON GROSS RENTAL OR LEASE FOR THE CONTINUED USE OR POSSESSION OF PERSONAL PROPERTY IN EXCESS OF TEN THOUSAND PESOS (P 10,000) ANNUALLY AND REAL PROPERTY USED IN BUSINESS WHICH THE PAYOR OR OBLIGOR HAS NOT TAKEN TITLE OR IS NOT TAKING TITLE, OR IN WHICH HAS NO EQUITY; POLES, SATELLITES, TRANSMISSION FACILITIES AND BILLBOARDS", .rate = "5.0", .category = .private },
    .{ .code = "WC110", .description = "CINEMATOGRAPHIC FILM RENTALS AND OTHER PAYMENTS TO RESIDENT INDIVIDUALS AND CORPORATE CINEMATOGRAPHIC FILM OWNERS, LESSORS OR DISTRIBUTORS", .rate = "5.0", .category = .private },
    .{ .code = "WC120", .description = "INCOME PAYMENTS TO CERTAIN CONTRACTORS ", .rate = "2.0", .category = .private },
    .{ .code = "WC139", .description = "GROSS COMMISSIONS OR SERVICE FEES OF CUSTOMS, INSURANCE, STOCK, IMMIGRATION AND COMMERCIAL BROKERS, FEES OF AGENTS OF PROFESSIONAL ENTERTAINERS AND REAL ESTATE SERVICE PRACTITIONERS (RESPS), (I.E. REAL ESTATE ONSULTANTS, REAL ESTATE APPRAISERS AND REAL ESTATE BROKERS) - IF GROSS INCOME FOR THE CURRENT YEAR DID NOT EXCEED P 720,000", .rate = "10.0", .category = .private },
    .{ .code = "WC140", .description = "GROSS COMMISSIONS OR SERVICE FEES OF CUSTOMS, INSURANCE, STOCK, IMMIGRATION AND COMMERCIAL BROKERS, FEES OF AGENTS OF PROFESSIONAL ENTERTAINERS AND REAL ESTATE SERVICE PRACTITIONERS (RESPS), (I.E. REAL ESTATE ONSULTANTS, REAL ESTATE APPRAISERS AND REAL ESTATE BROKERS) - IF GROSS INCOME EXCEEDS P 720,000", .rate = "15.0", .category = .private },
    .{ .code = "WC150", .description = "PROFESSIONAL FEES PAID TO MEDICAL PRACTITIONERS (INCLUDES DOCTORS OF MEDICINE DOCTORS OF VETERINARY SCIENCE & DENTISTS) BY HOSPITALS & CLINICS OR PAID DIRECTLY BY HEALTH MAINTENANCE ORGANIZATIONS (HMOS) AND/OR SIMILAR ESTABLISHMENTS - IF GROSS INCOME EXCEEDS P 720,000", .rate = "15.0", .category = .private },
    .{ .code = "WC151", .description = "PROFESSIONAL FEES PAID TO MEDICAL PRACTITIONERS (INCLUDES DOCTORS OF MEDICINE DOCTORS OF VETERINARY SCIENCE & DENTISTS) BY HOSPITALS & CLINICS OR PAID DIRECTLY BY HEALTH MAINTENANCE ORGANIZATIONS (HMOS) AND/OR SIMILAR ESTABLISHMENTS - IF GROSS INCOME FOR THE CURRENT YEAR DID NOT EXCEED P 720,000", .rate = "10.0", .category = .private },
    .{ .code = "WC156", .description = "INCOME PAYMENTS MADE BY CREDIT CARD COMPANIES", .rate = "0.5", .category = .private },
    .{ .code = "WC640", .description = "INCOME PAYMENTS MADE BY THE GOVERNMENT AND GOVERNMENT-OWNED AND CONTROLLED CORPORATIONS (GOCCS) TO ITS LOCAL/RESIDENT SUPPLIERS OF GOODS OTHER THAN THOSE COVERED BY OTHER RATES OF WITHHOLDING TAX", .rate = "1.0", .category = .private },
    .{ .code = "WC157", .description = "INCOME PAYMENTS MADE BY THE GOVERNMENT AND GOVERNMENT-OWNED AND CONTROLLED CORPORATIONS (GOCCS) TO ITS LOCAL/RESIDENT SUPPLIERS OF SERVICES OTHER THAN THOSE COVERED BY OTHER RATES OF WITHHOLDING TAX", .rate = "2.0", .category = .private },
    .{ .code = "WC158", .description = "INCOME PAYMENT MADE BY TOP WITHHOLDING AGENTS TO THEIR LOCAL/RESIDENT SUPPLIER OF GOODS OTHER THAN THOSE COVERED BY OTHER RATES OF WITHHOLDING TAX", .rate = "1.0", .category = .private },
    .{ .code = "WC160", .description = "INCOME PAYMENT MADE BY TOP WITHHOLDING AGENTS TO THEIR  LOCAL/RESIDENT SUPPLIER OF SERVICES OTHER THAN THOSE COVERED BY OTHER RATES OF WITHHOLDING TAX", .rate = "2.0", .category = .private },
    .{ .code = "WC515", .description = "COMMISSIONS, REBATES, DISCOUNTS AND OTHER SIMILAR CONSIDERATIONS PAID/ GRANTED TO INDEPENDENT AND/OR EXCLUSIVE SALES REPRESENTATIVES AND MARKETING AGENTS AND SUB-AGENTS OF COMPANIES, INCLUDING MULTI-LEVEL MARKETING COMPANIES - IF GROSS INCOME FOR THE CURRENT YEAR DID NOT EXCEED P 720,000", .rate = "10.0", .category = .private },
    .{ .code = "WC516", .description = "COMMISSIONS, REBATES, DISCOUNTS AND OTHER SIMILAR CONSIDERATIONS PAID/ GRANTED TO INDEPENDENT AND/OR EXCLUSIVE SALES REPRESENTATIVES AND MARKETING AGENTS AND SUB-AGENTS OF COMPANIES, INCLUDING MULTI-LEVEL MARKETING COMPANIES - IF GROSS INCOME EXCEEDS P 720,000", .rate = "15.0", .category = .private },
    .{ .code = "WC535", .description = "PAYMENTS MADE BY PRE-NEED COMPANIES TO FUNERAL PARLORS", .rate = "1.0", .category = .private },
    .{ .code = "WC540", .description = "TOLLING FEES PAID TO REFINERIES", .rate = "5.0", .category = .private },
    .{ .code = "WC610", .description = "INCOME PAYMENTS MADE TO SUPPLIERS OF AGRICULTURAL PRODUCTS IN EXCESS OF CUMULATIVE AMOUNT OF P 300,000 WITHIN THE SAME TAXABLE YEAR", .rate = "1.0", .category = .private },
    .{ .code = "WC630", .description = "INCOME PAYMENTS ON PURCHASES OF MINERALS, MINERAL PRODUCTS AND QUARRY RESOURCES, SUCH AS BUT NOT LIMITED TO SILVER, GOLD, MARBLE, GRANITE, GRAVEL, SAND, BOULDERS AND OTHER MINERAL PRODUCTS EXCEPT PURCHASES BY BANGKO SENTRAL NG PILIPINAS", .rate = "5.0", .category = .private },
    .{ .code = "WC632", .description = "INCOME PAYMENTS ON PURCHASES OF MINERALS, MINERAL PRODUCTS AND QUARRY RESOURCES BY BANGKO SENTRAL NG PILIPINAS (BSP) FROM GOLD MINERS/SUPPLIERS UNDER PD 1899, AS AMENDED BY RA NO. 7076", .rate = "1.0", .category = .private },
    .{ .code = "WC650", .description = "ON GROSS AMOUNT OF REFUND GIVEN BY MERALCO TO CUSTOMERS WITH ACTIVE CONTRACTS AS CLASSIFIED BY MERALCO", .rate = "15.0", .category = .private },
    .{ .code = "WC651", .description = "ON GROSS AMOUNT OF REFUND GIVEN BY MERALCO TO CUSTOMERS WITH TERMINATED CONTRACTS AS CLASSIFIED BY MERALCO", .rate = "15.0", .category = .private },
    .{ .code = "WC660", .description = "ON GROSS AMOUNT OF INTEREST ON THE REFUND OF METER DEPOSIT WHETHER PAID DIRECTLY TO THE CUSTOMERS OR APPLIED AGAINST CUSTOMER'S BILLINGS OF RESIDENTIAL AND GENERAL SERVICE CUSTOMERS WHOSE MONTHLY ELECTRICITY CONSUMPTION EXCEEDS 200 KWH AS CLASSIFIED BY MERALCO", .rate = "10.0", .category = .private },
    .{ .code = "WC661", .description = "ON GROSS AMOUNT OF INTEREST ON THE REFUND OF METER DEPOSIT WHETHER PAID DIRECTLY TO THE CUSTOMERS OR APPLIED AGAINST CUSTOMER'S BILLINGS OF  NON-RESIDENTIAL CUSTOMERS WHOSE MONTHLY ELECTRICITY CONSUMPTION EXCEEDS 200 KWH AS CLASSIFIED BY MERALCO", .rate = "10.0", .category = .private },
    .{ .code = "WC662", .description = "ON GROSS AMOUNT OF INTEREST ON THE REFUND OF METER DEPOSIT WHETHER PAID DIRECTLY TO THE CUSTOMERS OR APPLIED AGAINST CUSTOMER'S BILLINGS OF RESIDENTIAL AND GENERAL SERVICE CUSTOMERS WHOSE MONTHLY ELECTRICITY CONSUMPTION EXCEEDS 200 KWH AS CLASSIFIED BY OTHER ELECTRIC DISTRIBUTION UTILITIES (DU)", .rate = "10.0", .category = .private },
    .{ .code = "WC663", .description = "ON GROSS AMOUNT OF INTEREST ON THE REFUND OF METER DEPOSIT WHETHER PAID DIRECTLY TO THE CUSTOMERS OR APPLIED AGAINST CUSTOMER'S BILLINGS OF  NON- RESIDENTIAL CUSTOMERS WHOSE MONTHLY ELECTRICITY CONSUMPTION EXCEEDS 200 KWH AS CLASSIFIED BY OTHER ELECTRIC DISTRIBUTION UTILITIES (DU)", .rate = "15.0", .category = .private },
    .{ .code = "WC680", .description = "INCOME PAYMENTS MADE BY POLITICAL PARTIES AND CANDIDATES OF LOCAL AND NATIONAL ELECTIONS ON ALL THEIR PURCHASES OF GOODS AND SERVICES RELATED TO CAMPAIGN EXPENDITURES, AND INCOME PAYMENTS MADE BY INDIVIDUALS OR JURIDICAL PERSONS FOR THEIR PURCHASES OF GOODS AND SERVICES INTENDED TO BE GIVEN AS CAMPAIGN CONTRIBUTIONS TO POLITICAL PARTIES AND CANDIDATES", .rate = "5.0", .category = .private },
    .{ .code = "WC690", .description = "INCOME PAYMENTS RECEIVED BY REAL ESTATE INVESTMENT TRUST (REIT)", .rate = "1.0", .category = .private },
    .{ .code = "WC710", .description = "INTEREST INCOME DERIVED FROM ANY OTHER DEBT INSTRUMENTS NOT WITHIN THE COVERAGE OF DEPOSIT SUBSTITUTES AND REVENUE REGULATIONS NO. 14-2012 ", .rate = "15.0", .category = .private },
    .{ .code = "WC720", .description = "INCOME PAYMENTS ON LOCALLY PRODUCED RAW SUGAR", .rate = "1.0", .category = .private },
    .{ .code = "WC010", .description = "PROFESSIONAL (LAWYERS, CPAS, ENGINEERS, ETC.) - IF GROSS INCOME FOR THE CURRENT YEAR DID NOT EXCEED P 720,000", .rate = "10.0", .category = .government },
    .{ .code = "WC011", .description = "PROFESSIONAL (LAWYERS, CPAS, ENGINEERS, ETC.) - IF GROSS INCOME EXCEEDS P 720,000", .rate = "15.0", .category = .government },
    .{ .code = "WC020", .description = "PROFESSIONAL ENTERTAINERS SUCH AS, BUT NOT LIMITED TO ACTORS AND ACTRESSES, SINGERS, LYRICISTS, COMPOSERS, EMCEES - IF GROSS INCOME FOR THE CURRENT YEAR DID NOT EXCEED P 720,000", .rate = "10.0", .category = .government },
    .{ .code = "WC021", .description = "PROFESSIONAL ENTERTAINERS SUCH AS, BUT NOT LIMITED TO ACTORS AND ACTRESSES, SINGERS, LYRICISTS, COMPOSERS, EMCEES - IF GROSS INCOME EXCEEDS P 720,000", .rate = "15.0", .category = .government },
    .{ .code = "WC030", .description = "PROFESSIONAL ATHLETES INCLUDING BASKETBALL PLAYERS, PELOTARIS AND JOCKEYS - IF GROSS INCOME FOR THE CURRENT YEAR DID NOT EXCEED P 720,000", .rate = "10.0", .category = .government },
    .{ .code = "WC031", .description = "PROFESSIONAL ATHLETES INCLUDING BASKETBALL PLAYERS, PELOTARIS AND JOCKEYS - IF GROSS INCOME EXCEEDS P 720,000", .rate = "15.0", .category = .government },
    .{ .code = "WC040", .description = "ALL DIRECTORS AND PRODUCERS INVOLVED IN MOVIES, STAGE, RADIO, TELEVISION AND MUSICAL PRODUCTIONS - IF GROSS INCOME FOR THE CURRENT YEAR DID NOT EXCEED P 720,000", .rate = "10.0", .category = .government },
    .{ .code = "WC041", .description = "ALL DIRECTORS AND PRODUCERS INVOLVED IN MOVIES, STAGE, RADIO, TELEVISION AND MUSICAL PRODUCTIONS -  IF GROSS INCOME EXCEEDS P 720,000", .rate = "15.0", .category = .government },
    .{ .code = "WC050", .description = "MANAGEMENT AND TECHNICAL CONSULTANTS - IF GROSS INCOME FOR THE CURRENT YEAR DID NOT EXCEED P 720,000", .rate = "10.0", .category = .government },
    .{ .code = "WC051", .description = "MANAGEMENT AND TECHNICAL CONSULTANTS - IF GROSS INCOME EXCEEDS P 720,000", .rate = "15.0", .category = .government },
    .{ .code = "WC060", .description = "BUSINESS AND BOOKKEEPING AGENTS AND AGENCIES - IF GROSS INCOME FOR THE CURRENT YEAR DID NOT EXCEED P 720,000", .rate = "10.0", .category = .government },
    .{ .code = "WC061", .description = "BUSINESS AND BOOKKEEPING AGENTS AND AGENCIES - IF GROSS INCOME EXCEEDS P 720,000", .rate = "15.0", .category = .government },
    .{ .code = "WC070", .description = "INSURANCE AGENTS AND INSURANCE ADJUSTERS - IF GROSS INCOME FOR THE CURRENT YEAR DID NOT EXCEED P 720,000", .rate = "10.0", .category = .government },
    .{ .code = "WC071", .description = "INSURANCE AGENTS AND INSURANCE ADJUSTERS - IF GROSS INCOME EXCEEDS P 720,000", .rate = "15.0", .category = .government },
    .{ .code = "WC080", .description = "OTHER RECIPIENTS OF TALENT FEES - IF GROSS INCOME FOR THE CURRENT YEAR DID NOT EXCEED P 720,000", .rate = "10.0", .category = .government },
    .{ .code = "WC081", .description = "OTHER RECIPIENTS OF TALENT FEES - IF GROSS INCOME EXCEEDS P 720,000", .rate = "15.0", .category = .government },
    .{ .code = "WC100", .description = "RENTALS: ON GROSS RENTAL OR LEASE FOR THE CONTINUED USE OR POSSESSION OF PERSONAL PROPERTY IN EXCESS OF TEN THOUSAND PESOS (P 10,000) ANNUALLY AND REAL PROPERTY USED IN BUSINESS WHICH THE PAYOR OR OBLIGOR HAS NOT TAKEN TITLE OR IS NOT TAKING TITLE, OR IN WHICH HAS NO EQUITY; POLES, SATELLITES, TRANSMISSION FACILITIES AND BILLBOARDS", .rate = "5.0", .category = .government },
    .{ .code = "WC110", .description = "CINEMATOGRAPHIC FILM RENTALS AND OTHER PAYMENTS TO RESIDENT INDIVIDUALS AND CORPORATE CINEMATOGRAPHIC FILM OWNERS, LESSORS OR DISTRIBUTORS", .rate = "5.0", .category = .government },
    .{ .code = "WC120", .description = "INCOME PAYMENTS TO CERTAIN CONTRACTORS ", .rate = "2.0", .category = .government },
    .{ .code = "WC139", .description = "GROSS COMMISSIONS OR SERVICE FEES OF CUSTOMS, INSURANCE, STOCK, IMMIGRATION AND COMMERCIAL BROKERS, FEES OF AGENTS OF PROFESSIONAL ENTERTAINERS AND REAL ESTATE SERVICE PRACTITIONERS (RESPS), (I.E. REAL ESTATE ONSULTANTS, REAL ESTATE APPRAISERS AND REAL ESTATE BROKERS) - IF GROSS INCOME FOR THE CURRENT YEAR DID NOT EXCEED P 720,000", .rate = "10.0", .category = .government },
    .{ .code = "WC140", .description = "GROSS COMMISSIONS OR SERVICE FEES OF CUSTOMS, INSURANCE, STOCK, IMMIGRATION AND COMMERCIAL BROKERS, FEES OF AGENTS OF PROFESSIONAL ENTERTAINERS AND REAL ESTATE SERVICE PRACTITIONERS (RESPS), (I.E. REAL ESTATE ONSULTANTS, REAL ESTATE APPRAISERS AND REAL ESTATE BROKERS) - IF GROSS INCOME EXCEEDS P 720,000", .rate = "15.0", .category = .government },
    .{ .code = "WC150", .description = "PROFESSIONAL FEES PAID TO MEDICAL PRACTITIONERS (INCLUDES DOCTORS OF MEDICINE DOCTORS OF VETERINARY SCIENCE & DENTISTS) BY HOSPITALS & CLINICS OR PAID DIRECTLY BY HEALTH MAINTENANCE ORGANIZATIONS (HMOS) AND/OR SIMILAR ESTABLISHMENTS - IF GROSS INCOME EXCEEDS P 720,000", .rate = "15.0", .category = .government },
    .{ .code = "WC151", .description = "PROFESSIONAL FEES PAID TO MEDICAL PRACTITIONERS (INCLUDES DOCTORS OF MEDICINE DOCTORS OF VETERINARY SCIENCE & DENTISTS) BY HOSPITALS & CLINICS OR PAID DIRECTLY BY HEALTH MAINTENANCE ORGANIZATIONS (HMOS) AND/OR SIMILAR ESTABLISHMENTS - IF GROSS INCOME FOR THE CURRENT YEAR DID NOT EXCEED P 720,000", .rate = "10.0", .category = .government },
    .{ .code = "WC156", .description = "INCOME PAYMENTS MADE BY CREDIT CARD COMPANIES", .rate = "0.5", .category = .government },
    .{ .code = "WC640", .description = "INCOME PAYMENTS MADE BY THE GOVERNMENT AND GOVERNMENT-OWNED AND CONTROLLED CORPORATIONS (GOCCS) TO ITS LOCAL/RESIDENT SUPPLIERS OF GOODS OTHER THAN THOSE COVERED BY OTHER RATES OF WITHHOLDING TAX", .rate = "1.0", .category = .government },
    .{ .code = "WC157", .description = "INCOME PAYMENTS MADE BY THE GOVERNMENT AND GOVERNMENT-OWNED AND CONTROLLED CORPORATIONS (GOCCS) TO ITS LOCAL/RESIDENT SUPPLIERS OF SERVICES OTHER THAN THOSE COVERED BY OTHER RATES OF WITHHOLDING TAX", .rate = "2.0", .category = .government },
    .{ .code = "WC158", .description = "INCOME PAYMENT MADE BY TOP WITHHOLDING AGENTS TO THEIR LOCAL/RESIDENT SUPPLIER OF GOODS OTHER THAN THOSE COVERED BY OTHER RATES OF WITHHOLDING TAX", .rate = "1.0", .category = .government },
    .{ .code = "WC160", .description = "INCOME PAYMENT MADE BY TOP WITHHOLDING AGENTS TO THEIR  LOCAL/RESIDENT SUPPLIER OF SERVICES OTHER THAN THOSE COVERED BY OTHER RATES OF WITHHOLDING TAX", .rate = "2.0", .category = .government },
    .{ .code = "WC515", .description = "COMMISSIONS, REBATES, DISCOUNTS AND OTHER SIMILAR CONSIDERATIONS PAID/ GRANTED TO INDEPENDENT AND/OR EXCLUSIVE SALES REPRESENTATIVES AND MARKETING AGENTS AND SUB-AGENTS OF COMPANIES, INCLUDING MULTI-LEVEL MARKETING COMPANIES - IF GROSS INCOME FOR THE CURRENT YEAR DID NOT EXCEED P 720,000", .rate = "10.0", .category = .government },
    .{ .code = "WC516", .description = "COMMISSIONS, REBATES, DISCOUNTS AND OTHER SIMILAR CONSIDERATIONS PAID/ GRANTED TO INDEPENDENT AND/OR EXCLUSIVE SALES REPRESENTATIVES AND MARKETING AGENTS AND SUB-AGENTS OF COMPANIES, INCLUDING MULTI-LEVEL MARKETING COMPANIES - IF GROSS INCOME EXCEEDS P 720,000", .rate = "15.0", .category = .government },
    .{ .code = "WC535", .description = "PAYMENTS MADE BY PRE-NEED COMPANIES TO FUNERAL PARLORS", .rate = "1.0", .category = .government },
    .{ .code = "WC540", .description = "TOLLING FEES PAID TO REFINERIES", .rate = "5.0", .category = .government },
    .{ .code = "WC610", .description = "INCOME PAYMENTS MADE TO SUPPLIERS OF AGRICULTURAL PRODUCTS IN EXCESS OF CUMULATIVE AMOUNT OF P 300,000 WITHIN THE SAME TAXABLE YEAR", .rate = "1.0", .category = .government },
    .{ .code = "WC630", .description = "INCOME PAYMENTS ON PURCHASES OF MINERALS, MINERAL PRODUCTS AND QUARRY RESOURCES, SUCH AS BUT NOT LIMITED TO SILVER, GOLD, MARBLE, GRANITE, GRAVEL, SAND, BOULDERS AND OTHER MINERAL PRODUCTS EXCEPT PURCHASES BY BANGKO SENTRAL NG PILIPINAS", .rate = "5.0", .category = .government },
    .{ .code = "WC632", .description = "INCOME PAYMENTS ON PURCHASES OF MINERALS, MINERAL PRODUCTS AND QUARRY RESOURCES BY BANGKO SENTRAL NG PILIPINAS (BSP) FROM GOLD MINERS/SUPPLIERS UNDER PD 1899, AS AMENDED BY RA NO. 7076", .rate = "1.0", .category = .government },
    .{ .code = "WC650", .description = "ON GROSS AMOUNT OF REFUND GIVEN BY MERALCO TO CUSTOMERS WITH ACTIVE CONTRACTS AS CLASSIFIED BY MERALCO", .rate = "15.0", .category = .government },
    .{ .code = "WC651", .description = "ON GROSS AMOUNT OF REFUND GIVEN BY MERALCO TO CUSTOMERS WITH TERMINATED CONTRACTS AS CLASSIFIED BY MERALCO", .rate = "32.0", .category = .government },
    .{ .code = "WC660", .description = "ON GROSS AMOUNT OF INTEREST ON THE REFUND OF METER DEPOSIT WHETHER PAID DIRECTLY TO THE CUSTOMERS OR APPLIED AGAINST CUSTOMER'S BILLINGS OF RESIDENTIAL AND GENERAL SERVICE CUSTOMERS WHOSE MONTHLY ELECTRICITY CONSUMPTION EXCEEDS 200 KWH AS CLASSIFIED BY MERALCO", .rate = "10.0", .category = .government },
    .{ .code = "WC661", .description = "ON GROSS AMOUNT OF INTEREST ON THE REFUND OF METER DEPOSIT WHETHER PAID DIRECTLY TO THE CUSTOMERS OR APPLIED AGAINST CUSTOMER'S BILLINGS OF  NON-RESIDENTIAL CUSTOMERS WHOSE MONTHLY ELECTRICITY CONSUMPTION EXCEEDS 200 KWH AS CLASSIFIED BY MERALCO", .rate = "10.0", .category = .government },
    .{ .code = "WC662", .description = "ON GROSS AMOUNT OF INTEREST ON THE REFUND OF METER DEPOSIT WHETHER PAID DIRECTLY TO THE CUSTOMERS OR APPLIED AGAINST CUSTOMER'S BILLINGS OF RESIDENTIAL AND GENERAL SERVICE CUSTOMERS WHOSE MONTHLY ELECTRICITY CONSUMPTION EXCEEDS 200 KWH AS CLASSIFIED BY OTHER ELECTRIC DISTRIBUTION UTILITIES (DU)", .rate = "10.0", .category = .government },
    .{ .code = "WC663", .description = "ON GROSS AMOUNT OF INTEREST ON THE REFUND OF METER DEPOSIT WHETHER PAID DIRECTLY TO THE CUSTOMERS OR APPLIED AGAINST CUSTOMER'S BILLINGS OF  NON- RESIDENTIAL CUSTOMERS WHOSE MONTHLY ELECTRICITY CONSUMPTION EXCEEDS 200 KWH AS CLASSIFIED BY OTHER ELECTRIC DISTRIBUTION UTILITIES (DU)", .rate = "15.0", .category = .government },
    .{ .code = "WC680", .description = "INCOME PAYMENTS MADE BY POLITICAL PARTIES AND CANDIDATES OF LOCAL AND NATIONAL ELECTIONS ON ALL THEIR PURCHASES OF GOODS AND SERVICES RELATED TO CAMPAIGN EXPENDITURES, AND INCOME PAYMENTS MADE BY INDIVIDUALS OR JURIDICAL PERSONS FOR THEIR PURCHASES OF GOODS AND SERVICES INTENDED TO BE GIVEN AS CAMPAIGN CONTRIBUTIONS TO POLITICAL PARTIES AND CANDIDATES", .rate = "5.0", .category = .government },
    .{ .code = "WC690", .description = "INCOME PAYMENTS RECEIVED BY REAL ESTATE INVESTMENT TRUST (REIT)", .rate = "1.0", .category = .government },
    .{ .code = "WC710", .description = "INTEREST INCOME DERIVED FROM ANY OTHER DEBT INSTRUMENTS NOT WITHIN THE COVERAGE OF DEPOSIT SUBSTITUTES AND REVENUE REGULATIONS NO. 14-2012 ", .rate = "20.0", .category = .government },
    .{ .code = "WC720", .description = "INCOME PAYMENTS ON LOCALLY PRODUCED RAW SUGAR", .rate = "1.0", .category = .government },
    .{ .code = "WI820", .description = "ON THE GROSS REMITTANCES BY E-MARKETPLACE OPERATORS TO THE SELLERS/MERCHANTS FOR THE GOODS OR SERVICES SOLD/PAID THROUGH THEIR PLATFORM/FACILITY-INDIVIDUAL.", .rate = "0.5", .category = .private },
    .{ .code = "WI830", .description = "ON THE GROSS REMITTANCES BY DIGITAL FINANCIAL SERVICES PROVIDERS TO THE SELLERS/MERCHANTS FOR THE GOODS OR SERVICES SOLD/PAID THROUGH THEIR PLATFORM/FACILITY-INDIVIDUAL", .rate = "0.5", .category = .private },
    .{ .code = "WC820", .description = "ON THE GROSS REMITTANCES BY E-MARKETPLACE OPERATORS TO THE SELLERS/MERCHANTS FOR THE GOODS OR SERVICES SOLD/PAID THROUGH THEIR PLATFORM/FACILITY-CORPORATE", .rate = "0.5", .category = .private },
    .{ .code = "WC830", .description = "ON THE GROSS REMITTANCES BY DIGITAL FINANCIAL SERVICES PROVIDERS TO THE SELLERS/MERCHANTS FOR THE GOODS OR SERVICES SOLD/PAID THROUGH THEIR PLATFORM/FACILITY-CORPORATE", .rate = "0.5", .category = .private },
    .{ .code = "WI770", .description = "INCOME PAYMENTS MADE BY JOINT VENTURES, WHETHER INCORPORATED OR NOT, TAXABLE OR NON-TAXABLE, TO THEIR LOCAL/RESIDENT SUPPLIER OF GOODS. INDIVIDUAL", .rate = "1.0", .category = .private },
    .{ .code = "WI780", .description = "INCOME PAYMENTS MADE BY JOINT VENTURES, WHETHER INCORPORATED OR NOT, TAXABLE OR NON-TAXABLE, TO THEIR LOCAL/RESIDENT SUPPLIER OF SERVICES. INDIVIDUAL", .rate = "2.0", .category = .private },
    .{ .code = "WC770", .description = "INCOME PAYMENTS MADE BY JOINT VENTURES, WHETHER INCORPORATED OR NOT, TAXABLE OR NON-TAXABLE, TO THEIR LOCAL/RESIDENT SUPPLIER OF GOODS. CORPORATE", .rate = "1.0", .category = .private },
    .{ .code = "WC780", .description = "INCOME PAYMENTS MADE BY JOINT VENTURES, WHETHER INCORPORATED OR NOT, TAXABLE OR NON-TAXABLE, TO THEIR LOCAL/RESIDENT SUPPLIER OF SERVICES. CORPORATE", .rate = "2.0", .category = .private },
    .{ .code = "WC790", .description = "ON THE SHARE OF EACH CO-VENTURER/MEMBER FROM THE NET INCOME OF THE JOINT VENTURE/CONSORTIUM NOT TAXABLE AS CORPORATION PRIOR TO ACTUAL OR CONSTRUCTIVE DISTRIBUTION THEREOF. CORPORATE", .rate = "15.0", .category = .private },
    .{ .code = "WI840", .description = "INCOME PAYMENTS MADE BY TOP WITHHOLDING AGENTS, EITHER PRIVATE CORPORATION OR INDIVIDUALS, TO THE MANUFACTURERS AND DIRECT IMPORTERS OF MOTOR VEHICLES IN COMPLETELY BUILT UNITS (CBUs) OR SEMI-KNOCKDOWN (SKD) UNITS, MOTOR VEHICLE PARTS AND ACCESSORIES.", .rate = "0.5", .category = .private },
    .{ .code = "WC840", .description = "INCOME PAYMENTS MADE BY TOP WITHHOLDING AGENTS, EITHER PRIVATE CORPORATION OR INDIVIDUALS, TO THE MANUFACTURERS AND DIRECT IMPORTERS OF MOTOR VEHICLES IN COMPLETELY BUILT UNITS (CBUs) OR SEMI-KNOCKDOWN (SKD) UNITS, MOTOR VEHICLE PARTS AND ACCESSORIES.", .rate = "0.5", .category = .private },
    .{ .code = "WI850", .description = "INCOME PAYMENTS MADE BY TOP WITHHOLDING AGENTS, EITHER PRIVATE CORPORATION OR INDIVIDUALS, TO THE MANUFACTURERS AND DIRECT IMPORTERS OF MEDICINE/PHARMACEUTICAL PRODUCTS.", .rate = "0.5", .category = .private },
    .{ .code = "WC850", .description = "INCOME PAYMENTS MADE BY TOP WITHHOLDING AGENTS, EITHER PRIVATE CORPORATION OR INDIVIDUALS, TO THE MANUFACTURERS AND DIRECT IMPORTERS OF MEDICINE/PHARMACEUTICAL PRODUCTS.", .rate = "0.5", .category = .private },
    .{ .code = "WI860", .description = "INCOME PAYMENTS MADE BY TOP WITHHOLDING AGENTS, EITHER PRIVATE CORPORATION OR INDIVIDUALS, TO THE MANUFACTURERS AND DIRECT IMPORTERS OF SOLID OR LIQUID FUELS AND RELATED PRODUCTS.", .rate = "0.5", .category = .private },
    .{ .code = "WC860", .description = "INCOME PAYMENTS MADE BY TOP WITHHOLDING AGENTS, EITHER PRIVATE CORPORATION OR INDIVIDUALS, TO THE MANUFACTURERS AND DIRECT IMPORTERS OF SOLID OR LIQUID FUELS AND RELATED PRODUCTS.", .rate = "0.5", .category = .private },
};

pub const unreachable_records = [_]UnreachableRecord{
    .{ .code = "WI240", .description = "Distributive share of individual partners in a taxable partnership, association, joint account or joint venture or consortium;20" },
    .{ .code = "WI341", .description = "Royalties paid to NRAETB on cinematographic fils and similar works;20" },
    .{ .code = "WC212", .description = "Cash dividend payment by domestic corporation to citizens and resident aliens/NRFCs; 25" },
    .{ .code = "WC213", .description = "Property dividend payment by domestic corporation to citizens and resident aliens/NRFCs;25" },
};

pub const private_record_count: usize = 111;
pub const government_record_count: usize = 96;

pub fn countFor(category: Category) usize {
    var total: usize = 0;
    for (records) |record| {
        if (record.category == category) total += 1;
    }
    return total;
}

/// `getWithholdingAgentATC` narrows by category before matching a code, so
/// the same code can resolve to different rates in each category.
pub fn find(category: Category, code: []const u8) ?*const AtcRecord {
    for (&records) |*record| {
        if (record.category == category and std.mem.eql(u8, record.code, code)) {
            return record;
        }
    }
    return null;
}

pub fn isUnreachable(code: []const u8) bool {
    for (unreachable_records) |record| {
        if (std.mem.eql(u8, record.code, code)) return true;
    }
    return false;
}

/// Codes `changeATCRate` overrides for return periods at or before 2018.
const superseded_rates = [_]struct { code: []const u8, rate: []const u8 }{
    .{ .code = "WI650", .rate = "25.0" },
    .{ .code = "WC650", .rate = "25.0" },
    .{ .code = "WI651", .rate = "32.0" },
    .{ .code = "WC651", .rate = "32.0" },
    .{ .code = "WI663", .rate = "20.0" },
    .{ .code = "WC663", .rate = "20.0" },
    .{ .code = "WI710", .rate = "20.0" },
    .{ .code = "WC710", .rate = "20.0" },
};

/// `changeATCRate` lines 2665-2692, applied by `getWithholdingAgentATC` as
/// each row is built, so the rate tracks whatever Item 1 currently holds.
///
/// HTA compares the raw Item 1 string with `returnPeriod <= 2018`, which
/// coerces numerically. An empty year coerces to zero and therefore takes
/// the superseded branch, so a blank Item 1 yields the pre-2019 rates.
pub fn effectiveRate(
    code: []const u8,
    source_rate: []const u8,
    return_year: validation.Year,
) []const u8 {
    const year: i32 = switch (return_year) {
        .empty => 0,
        .value => |value| value,
    };
    if (year > 2018) return source_rate;
    for (superseded_rates) |entry| {
        if (std.mem.eql(u8, entry.code, code)) return entry.rate;
    }
    return source_rate;
}

test "1601EQ ATC catalog matches the source record accounting" {
    try std.testing.expectEqual(matched_record_count, records.len + unreachable_records.len);
    try std.testing.expectEqual(@as(usize, 211), matched_record_count);
    try std.testing.expectEqual(@as(usize, 207), records.len);
    try std.testing.expectEqual(@as(usize, 4), unreachable_records.len);
}

test "1601EQ ATC codes are unique inside a category and shared across them" {
    try std.testing.expectEqual(private_record_count, countFor(.private));
    try std.testing.expectEqual(government_record_count, countFor(.government));
    try std.testing.expectEqual(records.len, countFor(.private) + countFor(.government));

    for (records, 0..) |record, index| {
        try std.testing.expect(record.code.len > 0);
        try std.testing.expect(record.rate.len > 0);
        for (records[index + 1 ..]) |other| {
            if (record.category != other.category) continue;
            try std.testing.expect(!std.mem.eql(u8, record.code, other.code));
        }
    }

    // A code carried by both categories resolves independently in each.
    try std.testing.expect(find(.private, "WI010") != null);
    try std.testing.expect(find(.government, "WI010") != null);
}

test "1601EQ malformed source records reach neither dropdown" {
    try std.testing.expect(isUnreachable("WI240"));
    try std.testing.expect(isUnreachable("WI341"));
    try std.testing.expect(isUnreachable("WC212"));
    try std.testing.expect(isUnreachable("WC213"));

    for (unreachable_records) |missing| {
        try std.testing.expect(find(.private, missing.code) == null);
        try std.testing.expect(find(.government, missing.code) == null);
        // The rate is stranded in the description, which is the defect.
        try std.testing.expect(std.mem.indexOfScalar(u8, missing.description, ';') != null);
    }
}

test "1601EQ category token matches the optCategory values" {
    try std.testing.expectEqualStrings("P", Category.private.token());
    try std.testing.expectEqualStrings("G", Category.government.token());
    try std.testing.expectEqual(Category.private, Category.fromIdentity(.private).?);
    try std.testing.expectEqual(Category.government, Category.fromIdentity(.government).?);
    try std.testing.expect(Category.fromIdentity(.none) == null);
}

test "1601EQ superseded ATC rates apply only at or before the 2018 return period" {
    const y2018: validation.Year = .{ .value = 2018 };
    const y2019: validation.Year = .{ .value = 2019 };

    try std.testing.expectEqualStrings("25.0", effectiveRate("WI650", "15.0", y2018));
    try std.testing.expectEqualStrings("32.0", effectiveRate("WC651", "15.0", y2018));
    try std.testing.expectEqualStrings("20.0", effectiveRate("WI710", "15.0", y2018));
    try std.testing.expectEqualStrings("15.0", effectiveRate("WI650", "15.0", y2019));
    try std.testing.expectEqualStrings("15.0", effectiveRate("WC651", "15.0", y2019));

    // Codes outside the override list keep the source rate either way.
    try std.testing.expectEqualStrings("5.0", effectiveRate("WI010", "5.0", y2018));
    try std.testing.expectEqualStrings("5.0", effectiveRate("WI010", "5.0", y2019));
}

test "1601EQ blank Item 1 coerces to zero and takes the superseded rates" {
    try std.testing.expectEqualStrings("25.0", effectiveRate("WI650", "15.0", .empty));
    try std.testing.expectEqualStrings("15.0", effectiveRate("WI010", "15.0", .empty));
}

test "1601EQ every catalog rate survives a round trip through the rate rule" {
    const y2019: validation.Year = .{ .value = 2019 };
    for (records) |record| {
        try std.testing.expectEqualStrings(
            record.rate,
            effectiveRate(record.code, record.rate, y2019),
        );
    }
}
